const T={id:{app:"Catatan Keuangan",hello:"Pilih satu mata uang untuk digunakan ✨",totalBalance:"Total Saldo",offline:"100% Offline",accounts:"Akun & Saldo",income:"Pemasukan",expense:"Pengeluaran",transfer:"Transfer",summary:"Ringkasan Bulan Ini",budget:"Budget Bulanan",used:"Terpakai",chart:"Grafik Pengeluaran",saving:"Target Tabungan",calendar:"Kalender Transaksi",activity:"Transaksi Terbaru",clear:"Hapus",empty:"Belum ada transaksi",home:"Beranda",add:"Tambah",settings:"Pengaturan",amount:"Jumlah",category:"Kategori",account:"Akun",date:"Tanggal",note:"Catatan",save:"Simpan",language:"Bahasa",currency:"Mata Uang",currencyTip:"Pilih satu mata uang. Data tiap mata uang tersimpan terpisah dan tidak dikonversi.",simpleBudget:"Batas Budget",simpleGoal:"Target Tabungan",accountPlaceholder:"Contoh: BCA, DANA, Kas",backupInvalid:"File backup tidak valid.",backup:"Data & Backup",export:"Backup Data",import:"Pulihkan Data",backupNote:"Backup mencakup data kedua mata uang dan tidak menggunakan internet.",newAccount:"Tambah Akun",accountType:"Jenis Akun",accountName:"Nama Akun",opening:"Saldo Awal",from:"Dari",to:"Ke",bank:"Bank",ewallet:"E-Wallet",cash:"Cash",ic:["Gaji","Bonus","Bisnis","Hadiah","Lainnya"],ec:["Makanan","Transportasi","Belanja","Tagihan","Hiburan","Kesehatan","Lainnya"]},zh:{app:"私人記帳",hello:"請選擇一種貨幣使用 ✨",totalBalance:"總餘額",offline:"100% 離線",accounts:"帳戶與餘額",income:"收入",expense:"支出",transfer:"轉帳",summary:"本月摘要",budget:"每月預算",used:"已使用",chart:"支出圖表",saving:"儲蓄目標",calendar:"交易日曆",activity:"最近交易",clear:"刪除",empty:"目前沒有交易",home:"首頁",add:"新增",settings:"設定",amount:"金額",category:"分類",account:"帳戶",date:"日期",note:"備註",save:"儲存",language:"語言",currency:"貨幣",currencyTip:"請選擇一種貨幣。不同貨幣的資料分開儲存，不會進行匯率轉換。",simpleBudget:"預算上限",simpleGoal:"儲蓄目標",accountPlaceholder:"例如：銀行、電子錢包、現金",backupInvalid:"備份檔案無效。",backup:"資料與備份",export:"備份資料",import:"還原資料",backupNote:"備份包含兩種貨幣的資料，不需要網路。",newAccount:"新增帳戶",accountType:"帳戶類型",accountName:"帳戶名稱",opening:"初始餘額",from:"轉出",to:"轉入",bank:"銀行",ewallet:"電子錢包",cash:"現金",ic:["薪資","獎金","生意","禮物","其他"],ec:["飲食","交通","購物","帳單","娛樂","醫療","其他"]}};
const C={IDR:{s:"Rp",loc:"id-ID",name:"Rupiah (IDR)",short:"IDR"},MYR:{s:"RM",loc:"ms-MY",name:"Ringgit Malaysia (MYR)",short:"MYR"}};
const defaults=()=>({accounts:[{id:"cash",type:"cash",name:"Cash",opening:0}],tx:[],budget:0,goal:0,goalName:"Tabungan"});
const legacy=JSON.parse(localStorage.getItem("financeOfflineIDR")||"null");
let DB=JSON.parse(localStorage.getItem("financeOfflineMulti")||"null");
if(!DB){DB={lang:legacy?.lang||"id",cur:"IDR",data:{IDR:legacy?{accounts:legacy.accounts||defaults().accounts,tx:legacy.tx||[],budget:legacy.budget||0,goal:legacy.goal||0,goalName:legacy.goalName||"Tabungan"}:defaults(),MYR:defaults()}}}
DB.lang=DB.lang||"id";DB.cur=DB.cur&&C[DB.cur]?DB.cur:"IDR";DB.data=DB.data||{};for(const k of Object.keys(C))DB.data[k]=DB.data[k]||defaults();
let type="in";
const $=s=>document.querySelector(s),tr=k=>T[DB.lang][k],today=()=>new Date().toISOString().slice(0,10);
function state(){return DB.data[DB.cur]}
function money(n){return C[DB.cur].s+" "+new Intl.NumberFormat(C[DB.cur].loc,{maximumFractionDigits:2}).format(n)}
function save(){localStorage.setItem("financeOfflineMulti",JSON.stringify(DB));localStorage.removeItem("financeOfflineIDR")}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function icon(a){return a.type=="bank"?"🏦":a.type=="ewallet"?"📱":"💵"}
function acctBalance(id){let s=state(),a=s.accounts.find(x=>x.id==id),n=a?.opening||0;s.tx.forEach(x=>{if(x.type=="in"&&x.accountId==id)n+=x.amount;if(x.type=="out"&&x.accountId==id)n-=x.amount;if(x.type=="transfer"){if(x.from==id)n-=x.amount;if(x.to==id)n+=x.amount}});return n}
function fillAccountTypes(){$("#accountType").innerHTML=[["bank","🏦 "+tr("bank")],["ewallet","📱 "+tr("ewallet")],["cash","💵 "+tr("cash")]].map(x=>`<option value="${x[0]}">${x[1]}</option>`).join("");$("#accountName").placeholder=tr("accountPlaceholder")}
function render(){document.querySelectorAll("[data-i]").forEach(e=>e.textContent=tr(e.dataset.i));$("#badge").textContent=C[DB.cur].short;$("#lang").value=DB.lang;$("#cur").value=DB.cur;let s=state(),total=s.accounts.reduce((a,x)=>a+acctBalance(x.id),0),now=new Date(),y=now.getFullYear(),m=now.getMonth(),arr=s.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}),inc=arr.filter(x=>x.type=="in").reduce((a,x)=>a+x.amount,0),out=arr.filter(x=>x.type=="out").reduce((a,x)=>a+x.amount,0);$("#balance").textContent=money(total);$("#inc").textContent=money(inc);$("#exp").textContent=money(out);$("#month").textContent=now.toLocaleDateString(DB.lang=="zh"?"zh-TW":"id-ID",{month:"long",year:"numeric"});$("#budgetText").textContent=money(out)+" / "+money(s.budget);$("#bar").style.width=s.budget?Math.min(100,out/s.budget*100)+"%":"0%";let allin=s.tx.filter(x=>x.type=="in").reduce((a,x)=>a+x.amount,0);$("#goalName").textContent=s.goalName;$("#goalText").textContent=money(allin)+" / "+money(s.goal);$("#goalbar").style.width=s.goal?Math.min(100,allin/s.goal*100)+"%":"0%";drawAccounts();drawChart(arr);drawCal(y,m);drawList();fillAccounts();fillAccountTypes()}
function drawAccounts(){let s=state();$("#accountsList").innerHTML=s.accounts.map(a=>`<div class="accountCard"><div class="accountTop"><div class="accountIcon">${icon(a)}</div><div class="accountName">${esc(a.name)}</div></div><div class="accountBalance">${money(acctBalance(a.id))}</div><div class="accountType">${tr(a.type=="bank"?"bank":a.type=="ewallet"?"ewallet":"cash")}</div></div>`).join("")}
function fillAccounts(){let s=state(),opts=s.accounts.map(a=>`<option value="${a.id}">${icon(a)} ${esc(a.name)} — ${money(acctBalance(a.id))}</option>`).join("");$("#account").innerHTML=opts;$("#fromAccount").innerHTML=opts;$("#toAccount").innerHTML=opts}
function drawChart(arr){let ds=Array(7).fill(0);arr.filter(x=>x.type=="out").forEach(x=>{let d=new Date(x.date).getDate();ds[Math.min(6,Math.floor((d-1)/5))]+=x.amount});let max=Math.max(...ds,1);$("#bars").innerHTML=ds.map(v=>`<i class="baritem" style="height:${Math.max(4,v/max*100)}%"></i>`).join("")}
function drawCal(y,m){let s=state(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),names=DB.lang=="zh"?["日","一","二","三","四","五","六"]:["S","M","T","W","T","F","S"],out=names.map(x=>`<div class="day head">${x}</div>`).join("");let has=new Set(s.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}).map(x=>new Date(x.date).getDate()));for(let i=0;i<first;i++)out+="<div></div>";for(let d=1;d<=days;d++){let cls="day "+(has.has(d)?"has ":"")+(d==new Date().getDate()?"today":"");out+=`<div class="${cls}">${d}</div>`}$("#calendar").innerHTML=out;$("#calTitle").textContent=new Date(y,m).toLocaleDateString(DB.lang=="zh"?"zh-TW":"id-ID",{month:"long"})}
function name(id){return state().accounts.find(a=>a.id==id)?.name||"-"}
function drawList(){let s=state();$("#empty").style.display=s.tx.length?"none":"block";$("#list").innerHTML=[...s.tx].reverse().slice(0,15).map(x=>{let d=new Date(x.date).toLocaleDateString(DB.lang=="zh"?"zh-TW":"id-ID",{day:"2-digit",month:"short"});if(x.type=="transfer")return `<div class="tx"><div class="txicon">⇄</div><div class="txmain"><div class="txcat">${tr("transfer")}</div><div class="txdate">${d} · ${esc(name(x.from))} → ${esc(name(x.to))}</div></div><div class="txamt">${money(x.amount)}</div></div>`;return `<div class="tx"><div class="txicon">${x.type=="in"?"💰":"🛍️"}</div><div class="txmain"><div class="txcat">${esc(x.cat)}</div><div class="txdate">${d} · ${esc(name(x.accountId))}${x.note?" · "+esc(x.note):""}</div></div><div class="txamt ${x.type=="in"?"plus":"minus"}">${x.type=="in"?"+":"−"} ${money(x.amount)}</div></div>`}).join("")}
function openAdd(k){type=k;$("#modalTitle").textContent=tr(k=="in"?"income":"expense");$("#cat").innerHTML=(k=="in"?T[DB.lang].ic:T[DB.lang].ec).map(x=>`<option>${x}</option>`).join("");$("#amount").value="";$("#date").value=today();$("#note").value="";fillAccounts();$("#modal").classList.remove("hidden")}
$("#income").onclick=()=>openAdd("in");$("#expense").onclick=()=>openAdd("out");$("#add").onclick=()=>openAdd("out");$("#transfer").onclick=()=>{$("#transferDate").value=today();$("#transferNote").value="";fillAccounts();$("#transferModal").classList.remove("hidden")};
$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#closeTransfer").onclick=()=>$("#transferModal").classList.add("hidden");$("#settings").onclick=()=>$("#setmodal").classList.remove("hidden");$("#closes").onclick=()=>$("#setmodal").classList.add("hidden");
$("#addAccount").onclick=()=>{$("#accountName").value="";$("#opening").value=0;fillAccountTypes();$("#accountModal").classList.remove("hidden")};$("#closeAccount").onclick=()=>$("#accountModal").classList.add("hidden");
$("#lang").onchange=e=>{DB.lang=e.target.value;save();render()};$("#cur").onchange=e=>{let old=DB.cur;DB.cur=e.target.value;if(!C[DB.cur])DB.cur=old;save();render()};
$("#form").onsubmit=e=>{e.preventDefault();let n=Number($("#amount").value);if(!n)return;state().tx.push({type,amount:n,cat:$("#cat").value,accountId:$("#account").value,note:$("#note").value.trim(),date:$("#date").value+"T12:00:00"});save();$("#modal").classList.add("hidden");render()};
$("#transferForm").onsubmit=e=>{e.preventDefault();let n=Number($("#transferAmount").value),f=$("#fromAccount").value,t=$("#toAccount").value;if(!n||f==t)return alert(DB.lang=="id"?"Pilih dua akun yang berbeda.":"請選擇兩個不同的帳戶。");if(acctBalance(f)<n)return alert(DB.lang=="id"?"Saldo akun asal tidak cukup.":"轉出帳戶餘額不足。");state().tx.push({type:"transfer",amount:n,from:f,to:t,note:$("#transferNote").value.trim(),date:$("#transferDate").value+"T12:00:00"});save();$("#transferModal").classList.add("hidden");render()};
$("#accountForm").onsubmit=e=>{e.preventDefault();let n=$("#accountName").value.trim();if(!n)return;state().accounts.push({id:Date.now().toString(),type:$("#accountType").value,name:n,opening:Number($("#opening").value)||0});save();$("#accountModal").classList.add("hidden");render()};
function simple(kind){let s=state();$("#simple").classList.remove("hidden");$("#simpleTitle").textContent=kind=="goal"?tr("saving"):tr("budget");$("#simpleLabel").textContent=kind=="goal"?tr("simpleGoal"):tr("simpleBudget");$("#simpleInput").value=kind=="goal"?s.goal:s.budget;$("#simpleName").style.display=kind=="goal"?"block":"none";$("#simpleName").value=s.goalName;$("#simpleSave").onclick=()=>{if(kind=="goal"){s.goal=Number($("#simpleInput").value);s.goalName=$("#simpleName").value||"Tabungan"}else s.budget=Number($("#simpleInput").value);save();$("#simple").classList.add("hidden");render()}}
$("#budgetBtn").onclick=()=>simple("budget");$("#goalBtn").onclick=()=>simple("goal");$("#simpleClose").onclick=()=>$("#simple").classList.add("hidden");$("#clear").onclick=()=>{if(state().tx.length&&confirm(DB.lang=="id"?"Hapus semua transaksi pada mata uang ini?":"刪除此貨幣的全部交易？")){state().tx=[];save();render()}};
$("#export").onclick=()=>{let blob=new Blob([JSON.stringify(DB,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="backup-keuangan-IDR-MYR.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#import").onclick=()=>$("#file").click();$("#file").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.data&&x.data.IDR&&x.data.MYR){DB=x}else if(x.tx&&x.accounts){DB={lang:x.lang||"id",cur:"IDR",data:{IDR:x,MYR:defaults()}}}else throw 0;DB.lang=DB.lang||"id";DB.cur=C[DB.cur]?DB.cur:"IDR";for(const k of Object.keys(C))DB.data[k]=DB.data[k]||defaults();save();render();alert(DB.lang=="id"?"Data berhasil dipulihkan.":"資料還原成功。")}catch{alert(tr("backupInvalid"))}};r.readAsText(f)};
render();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
